sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating a image with dockerfile"
  - docker build -t inyeob/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true inyeob/docker-react-app npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-practice-plaform"
  env: "Dockerpracticeplaform-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-133275553188"
  path: "docker-practice-plaform" 
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY