sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating a image with dockerfile"
  - docker build -t inyeob/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true inyeob/docker-react-app npm run test -- --coverage

# after_success:
#   - echo "Test success"